[book]
authors = []
language = "pt-br"
multilingual = false
src = "src"
title = "Linguagem C"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Xumaquer/mdbook-linguagem-c"